### PR TITLE
Added USB-IF to AG-03

### PR DESCRIPTION
**Pull request by tbause**
https://github.com/SMPTE/ag-03/issues/7

### CODE REVIEW

**Review by palemieux — CHANGES_REQUESTED** [review]
@tbause Please add to the issue #7 the justification using the template at https://doc.smpte-doc.org/ag-03/3d52bf5896efbcbf22adddf2a64823df3d0bb69d/

**Review by SteveLLamb — APPROVED** [review]

**Comment by SteveLLamb** [comment]
Closes #7

**Review by palemieux — APPROVED** [review]

**Comment by tbause** [comment]
Closes #7

**Comment by tbause** [comment]
Closes #7

**Pull request merged**
